version: '2.1'

services:
  django:
    build: .
    environment:
      - "DATABASE_URL=sqlite:////data/db.sqlite3"
      - "SECRET_KEY=${SECRET_KEY}"
      - "ALLOWED_HOSTS=${DOMAIN}"
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data/:/data
