version: '2.1'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  django:
    build: .
    environment:
      - "DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres"
      - "SECRET_KEY=${SECRET_KEY}"
      - "ALLOWED_HOSTS=${DOMAIN}"
    restart: unless-stopped
    ports:
      - "8000:8000"
